name: ai5_project1
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.4.1
  - torchvision=0.19.1
  - torchaudio=2.4.1
  - pytorch-cuda=12.1
  - pip
  - pip:
      - ultralytics==8.2.68
      - albumentations==1.3.1
      - opencv-python==4.10.0.84
      - matplotlib==3.9.2
      - pandas==2.2.3
      - PyYAML==6.0.2
      - tqdm==4.66.5
