name: tablet_detection
channels:
  - pytorch
  - defaults
dependencies:
  - aom=3.6.0=hcec6c5f_0
  - blas=1.0=mkl
  - brotlicffi=1.0.9.2=py311h6d0c2b6_1
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.7.15=hecd8cb5_0
  - cairo=1.16.0=h08824b9_6
  - cffi=1.17.1=py311h9205ec4_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cpuonly=2.0=0
  - dav1d=1.2.1=h6c40b1e_0
  - expat=2.7.1=h6d0c2b6_0
  - fontconfig=2.14.1=h269ac6a_3
  - freetype=2.13.3=h02243ff_0
  - fribidi=1.0.10=haf1e3a3_0
  - gettext=0.21.0=h4e8c18a_2
  - gmp=6.3.0=h6d0c2b6_0
  - gmpy2=2.2.1=py311h2cec913_0
  - graphite2=1.3.14=he9d5cce_1
  - harfbuzz=10.2.0=h060d35a_1
  - icu=73.1=hcec6c5f_0
  - idna=3.7=py311hecd8cb5_0
  - intel-openmp=2023.1.0=ha357a0b_43548
  - jinja2=3.1.6=py311hecd8cb5_0
  - jpeg=9e=h46256e1_3
  - lcms2=2.16=h31d93a5_1
  - lerc=4.0.0=h6d0c2b6_0
  - libavif=1.1.1=h46256e1_0
  - libcxx=19.1.7=haebbb44_3
  - libdeflate=1.22=h46256e1_0
  - libffi=3.4.4=hecd8cb5_1
  - libglib=2.84.2=heb90364_0
  - libiconv=1.16=h6c40b1e_3
  - libjpeg-turbo=2.0.0=hca72f7f_0
  - libpng=1.6.39=h6c40b1e_0
  - libtiff=4.7.0=h2dfa3ea_0
  - libwebp-base=1.3.2=h46256e1_1
  - libxml2=2.13.8=h6070cd6_0
  - llvm-openmp=19.1.7=h5048363_2
  - lz4-c=1.9.4=hcec6c5f_1
  - markupsafe=3.0.2=py311h46256e1_0
  - mkl=2023.1.0=h8e150cf_43560
  - mkl-service=2.4.0=py311h46256e1_2
  - mkl_fft=1.3.8=py311h6c40b1e_0
  - mkl_random=1.2.4=py311ha357a0b_0
  - mpc=1.3.1=h46256e1_0
  - mpfr=4.2.1=h46256e1_0
  - mpmath=1.3.0=py311hecd8cb5_0
  - ncurses=6.5=h923df54_0
  - numpy=1.26.4=py311h728a8a3_0
  - numpy-base=1.26.4=py311h53bf9ac_0
  - openjpeg=2.5.2=h2d09ccc_1
  - openssl=3.0.17=hee2dfae_0
  - pcre2=10.42=h9b97e30_1
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=hb254d66_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pysocks=1.7.1=py311hecd8cb5_0
  - python=3.11.13=hbff2529_0
  - pytorch=2.2.2=py3.11_0
  - pytorch-mutex=1.0=cpu
  - readline=8.3=h49f2429_0
  - sqlite=3.50.2=hc8b0dd6_1
  - tbb=2021.8.0=ha357a0b_0
  - tk=8.6.15=h3a5a201_0
  - torchaudio=2.2.2=py311_cpu
  - torchvision=0.17.2=py311_cpu
  - wheel=0.45.1=py311hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - yaml=0.2.5=haf1e3a3_0
  - zlib=1.2.13=h4b97444_1
  - zstd=1.5.6=h138b38a_0
  - pip:
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - attrs==25.4.0
      - certifi==2024.2.2
      - colorama==0.4.6
      - contourpy==1.3.0
      - cycler==0.12.1
      - eval-type-backport==0.2.2
      - filelock==3.13.4
      - fonttools==4.60.1
      - fsspec==2024.3.1
      - imageio==2.34.1
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - joblib==1.5.2
      - jsonschema==4.21.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.5
      - matplotlib==3.8.4
      - networkx==3.2.1
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.11.0.86
      - packaging==24.0
      - pandas==2.2.2
      - pillow==10.3.0
      - psutil==5.9.8
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.1
      - referencing==0.34.0
      - requests==2.31.0
      - rpds-py==0.18.0
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - seaborn==0.13.2
      - setuptools==69.5.1
      - simsimd==6.5.3
      - six==1.17.0
      - stringzilla==4.2.1
      - sympy==1.12.1
      - threadpoolctl==3.4.0
      - tqdm==4.66.2
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - zipp==3.18.1
prefix: /Users/morgan/Desktop/anaconda/anaconda3/envs/tablet_detection
